language: java
dist: trusty
sudo: false
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests
  skip_cleanup: true
  on:
    tags: true
