language: java
dist: trusty
sudo: false
jdk:
- openjdk8
after_success:
- mvn test
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: mvn deploy -DskipTests
  on:
    tag: true
